In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from sklearn import model_selection
from sklearn import metrics
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

## Question 1

In [98]:
##Probability of Sunny
S=5.0/14
##Probability of Yes
Y=9.0/14
##Probability of (Sunny/Yes)
P=3.0/9
##Probability of (Yes/Sunny)
Q=(P*Y)/S
Q

0.6

## Question 2

In [99]:
df=datasets.load_iris()

In [100]:
p=df.data
q=df.target

In [101]:
p_train,p_test,q_train,q_test = train_test_split(p,q,test_size=0.3)
p_train.shape , p_test.shape

((105L, 4L), (45L, 4L))

In [102]:
## Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB

In [103]:
model=GaussianNB()

In [104]:
model.fit(p,q)

GaussianNB(priors=None)

In [105]:
model.fit(p,q)

GaussianNB(priors=None)

In [106]:
pred=model.predict(p)

In [107]:
metrics.accuracy_score(q,pred)*100

96.0

In [108]:
print(classification_report(q,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.94      0.94      0.94        50
          2       0.94      0.94      0.94        50

avg / total       0.96      0.96      0.96       150



In [109]:
print(confusion_matrix(q,pred))

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]


In [110]:
## Multinomial Naive Bayes 
from sklearn.naive_bayes import MultinomialNB

In [111]:
p_train,p_test,q_train,q_test = train_test_split(p,q,test_size=0.3)
p_train.shape , p_test.shape

((105L, 4L), (45L, 4L))

In [112]:
m=MultinomialNB()

In [113]:
m.fit(p,q)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [114]:
predi=m.predict(p)

In [115]:
metrics.accuracy_score(q,predi)*100

95.33333333333334

In [116]:
print(classification_report(q,predi))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.94      0.92      0.93        50
          2       0.92      0.94      0.93        50

avg / total       0.95      0.95      0.95       150



In [117]:
print(confusion_matrix(q,predi))

[[50  0  0]
 [ 0 46  4]
 [ 0  3 47]]
