In [69]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split

## Question 1
Loading the dataset from sklearn

In [70]:
digit=datasets.load_digits()

In [71]:
p=digit.data

In [72]:
q=digit.target

## Question 2
Spliting the dataset

In [73]:
p_train,p_test,q_train,q_test = train_test_split(p,q,test_size=0.4)
p_train.shape , p_test.shape

((1078L, 64L), (719L, 64L))

## Question 3
Using SVM with kernels
## a. Linear

In [74]:
m=SVC(kernel="linear")

In [75]:
m.fit(p_train,q_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [76]:
pred=m.predict(p_test)

In [77]:
metrics.accuracy_score(q_test,pred)

0.9819193324061196

In [78]:
print(metrics.confusion_matrix(q_test,pred))      ## Printing Confusion Matrix

[[69  0  0  0  0  0  0  0  0  0]
 [ 0 75  0  0  0  0  0  0  0  0]
 [ 0  1 73  0  0  0  0  0  0  0]
 [ 0  0  0 71  0  0  0  0  1  0]
 [ 0  0  0  0 68  0  0  0  0  0]
 [ 0  0  0  0  0 68  1  0  0  0]
 [ 1  0  0  0  0  0 70  0  0  0]
 [ 0  0  0  0  0  0  0 71  0  0]
 [ 0  4  0  0  0  0  0  0 73  0]
 [ 0  0  0  2  0  3  0  0  0 68]]


In [79]:
print(metrics.classification_report(q_test,pred))      ## Printing Classification Report

             precision    recall  f1-score   support

          0       0.99      1.00      0.99        69
          1       0.94      1.00      0.97        75
          2       1.00      0.99      0.99        74
          3       0.97      0.99      0.98        72
          4       1.00      1.00      1.00        68
          5       0.96      0.99      0.97        69
          6       0.99      0.99      0.99        71
          7       1.00      1.00      1.00        71
          8       0.99      0.95      0.97        77
          9       1.00      0.93      0.96        73

avg / total       0.98      0.98      0.98       719



## b. Poly

In [80]:
m2=SVC(kernel="poly")

In [81]:
m2.fit(p_train,q_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [82]:
pred2=m2.predict(p_test)

In [83]:
metrics.accuracy_score(q_test,pred2)*100

99.02642559109874

In [84]:
print(metrics.confusion_matrix(q_test,pred2))     ## Printing Confusion Matrix

[[69  0  0  0  0  0  0  0  0  0]
 [ 0 75  0  0  0  0  0  0  0  0]
 [ 0  0 74  0  0  0  0  0  0  0]
 [ 0  0  0 71  0  0  0  0  1  0]
 [ 0  0  0  0 68  0  0  0  0  0]
 [ 0  0  0  0  0 68  1  0  0  0]
 [ 0  0  0  0  0  0 70  0  1  0]
 [ 0  0  0  0  0  0  0 71  0  0]
 [ 0  2  0  0  0  0  0  0 75  0]
 [ 0  0  0  1  0  1  0  0  0 71]]


In [85]:
print(metrics.classification_report(q_test,pred2))      ## Printing Classification Report

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        69
          1       0.97      1.00      0.99        75
          2       1.00      1.00      1.00        74
          3       0.99      0.99      0.99        72
          4       1.00      1.00      1.00        68
          5       0.99      0.99      0.99        69
          6       0.99      0.99      0.99        71
          7       1.00      1.00      1.00        71
          8       0.97      0.97      0.97        77
          9       1.00      0.97      0.99        73

avg / total       0.99      0.99      0.99       719



## c. Gaussian

In [86]:
m3=SVC()

In [87]:
m3.fit(p_train,q_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [88]:
pred3=m3.predict(p_test)

In [89]:
metrics.accuracy_score(q_test,pred3)

0.4144645340751043

In [90]:
print(metrics.confusion_matrix(q_test,pred3))      ## Printing Confusion Matrix

[[35  0  0  0  0 34  0  0  0  0]
 [ 0 22  0  0  0 53  0  0  0  0]
 [ 0  0 12  0  0 62  0  0  0  0]
 [ 0  0  0 31  0 41  0  0  0  0]
 [ 0  0  0  0 42 26  0  0  0  0]
 [ 0  0  0  0  0 69  0  0  0  0]
 [ 0  0  0  0  0 23 48  0  0  0]
 [ 0  0  0  0  0 45  0 26  0  0]
 [ 0  0  0  0  0 77  0  0  0  0]
 [ 0  0  0  0  0 60  0  0  0 13]]


In [91]:
print(metrics.classification_report(q_test,pred3))      ## Printing Classification Report

             precision    recall  f1-score   support

          0       1.00      0.51      0.67        69
          1       1.00      0.29      0.45        75
          2       1.00      0.16      0.28        74
          3       1.00      0.43      0.60        72
          4       1.00      0.62      0.76        68
          5       0.14      1.00      0.25        69
          6       1.00      0.68      0.81        71
          7       1.00      0.37      0.54        71
          8       0.00      0.00      0.00        77
          9       1.00      0.18      0.30        73

avg / total       0.81      0.41      0.46       719



## d. Sigmoid

In [92]:
m4=SVC(kernel="sigmoid")

In [93]:
m4.fit(p_train,q_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [94]:
pred4=m4.predict(p_test)

In [95]:
metrics.accuracy_score(q_test,pred4)*100

9.596662030598054

In [96]:
print(metrics.confusion_matrix(q_test,pred3))    ## Printing Confusion Matrix

[[35  0  0  0  0 34  0  0  0  0]
 [ 0 22  0  0  0 53  0  0  0  0]
 [ 0  0 12  0  0 62  0  0  0  0]
 [ 0  0  0 31  0 41  0  0  0  0]
 [ 0  0  0  0 42 26  0  0  0  0]
 [ 0  0  0  0  0 69  0  0  0  0]
 [ 0  0  0  0  0 23 48  0  0  0]
 [ 0  0  0  0  0 45  0 26  0  0]
 [ 0  0  0  0  0 77  0  0  0  0]
 [ 0  0  0  0  0 60  0  0  0 13]]


In [97]:
print(metrics.classification_report(q_test,pred4))     ## Printing Classification Report

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        69
          1       0.00      0.00      0.00        75
          2       0.00      0.00      0.00        74
          3       0.00      0.00      0.00        72
          4       0.00      0.00      0.00        68
          5       0.10      1.00      0.18        69
          6       0.00      0.00      0.00        71
          7       0.00      0.00      0.00        71
          8       0.00      0.00      0.00        77
          9       0.00      0.00      0.00        73

avg / total       0.01      0.10      0.02       719

