In [1]:
import numpy as pd
import pandas as df
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn import datasets
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import train_test_split

## Question 1

In [2]:
digit=datasets.load_wine()
p=digit.data
q=digit.target

In [3]:
p_train,p_test,q_train,q_test = train_test_split(p,q,test_size=0.3)

## Question 2
a. Bagged Decision Tree

In [4]:
m1=DecisionTreeClassifier()
#m1.fit(p_train,q_train)
esti1=BaggingClassifier(base_estimator=m1)
esti1.fit(p_train,q_train)
pred1=esti1.predict(p_test)
metrics.accuracy_score(q_test,pred1)

1.0

In [5]:
print(metrics.classification_report(q_test,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        21
          1       1.00      1.00      1.00        19
          2       1.00      1.00      1.00        14

avg / total       1.00      1.00      1.00        54



In [6]:
print(metrics.confusion_matrix(q_test,pred1))

[[21  0  0]
 [ 0 19  0]
 [ 0  0 14]]


b. Random Forest Classification

In [7]:
esti2=RandomForestClassifier(n_estimators=100)
esti2.fit(p_train,q_train)
pred2=esti2.predict(p_test)
metrics.accuracy_score(q_test,pred2)*100

100.0

In [8]:
print(metrics.classification_report(q_test,pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        21
          1       1.00      1.00      1.00        19
          2       1.00      1.00      1.00        14

avg / total       1.00      1.00      1.00        54



In [9]:
print(metrics.confusion_matrix(q_test,pred2))

[[21  0  0]
 [ 0 19  0]
 [ 0  0 14]]


c. Stochastic Gradient Boosting Classification

In [11]:
esti3=GradientBoostingClassifier(n_estimators=100)
esti3.fit(p_train,q_train)
pred3=esti3.predict(p_test)
metrics.accuracy_score(q_test,pred3)*100

98.14814814814815

In [12]:
print(metrics.classification_report(q_test,pred3))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        21
          1       1.00      0.95      0.97        19
          2       0.93      1.00      0.97        14

avg / total       0.98      0.98      0.98        54



In [13]:
print(metrics.confusion_matrix(q_test,pred3))

[[21  0  0]
 [ 0 18  1]
 [ 0  0 14]]


d. Voting Ensemble (Decision Tree, Logistic Regression, SVM)

In [14]:
arr=[]
model1=LogisticRegression()
arr.append(("Logistic",model1))
model2=DecisionTreeClassifier()
arr.append(("Cart",model2))
model3=SVC()
arr.append(("SVM",model3))
model=VotingClassifier(arr).fit(p_test,q_test)
pred=model.predict(p_test)
metrics.accuracy_score(q_test,pred)

C:\Users\DIPANSHI\Anaconda2\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


1.0

In [15]:
print(metrics.classification_report(q_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        21
          1       1.00      1.00      1.00        19
          2       1.00      1.00      1.00        14

avg / total       1.00      1.00      1.00        54



In [16]:
print(metrics.confusion_matrix(q_test,pred))

[[21  0  0]
 [ 0 19  0]
 [ 0  0 14]]
