In [11]:
import numpy as np

## Question 1

In [14]:
a = np.random.random([10,1])

In [17]:
a

array([[0.6232346 ],
       [0.86161919],
       [0.13887984],
       [0.93117963],
       [0.50928689],
       [0.22966467],
       [0.38237553],
       [0.77421284],
       [0.2662903 ],
       [0.25283593]])

In [20]:
##mean
np.mean(a)

0.4969579425212318

## Question 2

In [23]:
b = np.random.random([20,1])

In [25]:
b

array([[0.22125942],
       [0.48780854],
       [0.45723494],
       [0.63922793],
       [0.56935674],
       [0.35997268],
       [0.87143461],
       [0.04026107],
       [0.5535145 ],
       [0.75354131],
       [0.70962734],
       [0.46658602],
       [0.99927487],
       [0.81646111],
       [0.50039524],
       [0.48944906],
       [0.08307293],
       [0.86665847],
       [0.95306468],
       [0.15808033]])

In [27]:
#Variance
np.var(b)

0.07576778994060604

In [29]:
#Standard Deviation
np.std(b)

0.2752594956411241

## Question 3

In [32]:
A = np.random.random([10,20])

In [34]:
B = np.random.random([20,25])

In [36]:
#Matrix Multiplication
C = np.dot(A,B)

In [38]:
C

array([[4.12750157, 3.20297485, 5.86339609, 3.99381079, 4.68329561,
        3.6403465 , 3.84159759, 4.64146116, 3.92448124, 4.14977397,
        4.27193468, 4.22260026, 3.5617703 , 4.53292645, 4.98672197,
        4.57473817, 3.15031798, 4.19480854, 4.83258767, 3.60841531,
        3.79631142, 4.60776426, 3.28845501, 3.163031  , 4.34127753],
       [5.23343803, 4.27576174, 6.17394833, 4.80316204, 5.48675412,
        4.82543724, 4.71368715, 5.76152605, 5.4051325 , 5.59054134,
        5.10710963, 4.7027988 , 4.87861352, 6.12913204, 5.78579283,
        4.79727599, 4.77184141, 5.93384623, 5.35279886, 3.73342453,
        4.43173506, 4.60887234, 4.93466749, 4.3156774 , 5.63153118],
       [6.39738745, 5.54274869, 8.52444422, 6.1979674 , 6.87315141,
        6.47661162, 5.71792914, 7.50796346, 7.05678381, 6.4641663 ,
        6.72300713, 6.23343373, 6.51025612, 7.28658388, 7.13663168,
        6.42066636, 5.88371888, 7.11567361, 7.21699212, 5.74937868,
        5.4897508 , 5.99284776, 6.08739884, 5.

In [40]:
C.shape

(10L, 25L)

In [42]:
np.sum(C)

1238.9544475628034

## Question 4

In [44]:
p = np.arange(10).reshape(10,1)

In [46]:
print(p.T)

[[0 1 2 3 4 5 6 7 8 9]]


In [48]:
def sigmoid(p):
    return 1/(1 + np.exp(-p))

In [49]:
print(sigmoid(p))

[[0.5       ]
 [0.73105858]
 [0.88079708]
 [0.95257413]
 [0.98201379]
 [0.99330715]
 [0.99752738]
 [0.99908895]
 [0.99966465]
 [0.99987661]]
