In [27]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import metrics
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

## Question 1
Importing dataset

In [28]:
digit=datasets.load_digits()
p=digit.data
q=digit.target

In [29]:
p.shape,q.shape

((1797L, 64L), (1797L,))

## Question 2
Perform Feature Scaling

In [30]:
p=preprocessing.scale(p)

In [31]:
df=pd.DataFrame(p)
df.head()

0         1         2         3         4         5         6         7   \
0  0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724 -0.125023   
1  0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724 -0.125023   
2  0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724 -0.125023   
3  0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724 -0.125023   
4  0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724 -0.125023   

         8         9     ...           54        55        56        57  \
0 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
1 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
2 -0.059078 -0.624009    ...     0.259230 -0.209785 -0.023596 -0.299081   
3 -0.059078  1.879691    ...     1.072563 -0.209785 -0.023596 -0.299081   
4 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   

         58        59        60        61        62        63  
0  0.086719  0.208293 -0.366771 -1.146647 -0.505670 -0.196008  
1 -1.089383 -0.249010  0.849632  0.548561 -0.505670 -0.196008  
2 -1.089383 -2.078218 -0.164037  1.565686  1.695137 -0.196008  
3  0.282736  0.208293  0.241430  0.379040 -0.505670 -0.196008  
4 -1.089383 -2.306869  0.849632 -0.468564 -0.505670 -0.196008  

[5 rows x 64 columns]

## Question 3
Split data in Training and Testing sets

In [32]:
p_train,p_test,q_train,q_test = train_test_split(p,q,test_size=0.3)

## Question 4
Perform PCA

In [33]:
pca = PCA(n_components=16)
principalComponents = pca.fit_transform(p)
principalComponents

array([[ 1.91421758, -0.9544829 , -3.9460405 , ..., -0.19155761,
         0.8561388 , -0.08283397],
       [ 0.58894734,  0.92449294,  3.92455537, ..., -0.38103146,
        -0.72550067,  0.21570771],
       [ 1.30204935, -0.31725284,  3.02331124, ..., -0.98161514,
        -1.20005447, -0.422439  ],
       ...,
       [ 1.02260093, -0.1479055 ,  2.46995707, ...,  0.28443876,
         0.32845481, -1.16883382],
       [ 1.07605676, -0.38109781, -2.4557598 , ..., -0.72109208,
         0.04352898, -0.09141161],
       [-1.25769598, -2.22762014,  0.28355332, ...,  0.7945827 ,
         1.76927497, -0.27277679]])

In [34]:
p=principalComponents
p.shape,q.shape

((1797L, 16L), (1797L,))

## Question 5
Perform Logistic Regression

In [35]:
reg = LogisticRegression()
reg.fit(p_train,q_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [36]:
pred = reg.predict(p_test)

## Question 6
a.Accuracy Score

In [37]:
metrics.accuracy_score(q_test,pred)*100

97.03703703703704

b.Confusion Matrix

In [38]:
print(confusion_matrix(q_test,pred))

[[53  0  0  0  0  1  0  0  0  0]
 [ 0 50  2  0  0  0  0  0  0  0]
 [ 0  0 53  1  0  0  0  0  0  0]
 [ 0  0  1 56  0  0  0  0  2  1]
 [ 0  0  0  0 40  0  0  0  0  0]
 [ 0  0  0  0  0 64  0  0  0  1]
 [ 0  1  0  0  0  0 62  0  0  0]
 [ 0  0  0  0  0  0  0 53  0  1]
 [ 0  3  0  0  1  0  0  0 46  0]
 [ 0  0  0  0  0  0  0  1  0 47]]


c.Classification Report

In [39]:
print(classification_report(q_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        54
          1       0.93      0.96      0.94        52
          2       0.95      0.98      0.96        54
          3       0.98      0.93      0.96        60
          4       0.98      1.00      0.99        40
          5       0.98      0.98      0.98        65
          6       1.00      0.98      0.99        63
          7       0.98      0.98      0.98        54
          8       0.96      0.92      0.94        50
          9       0.94      0.98      0.96        48

avg / total       0.97      0.97      0.97       540

